/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdio.h"
#include "mygui.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x0A)
#define ID_MENU_0 (GUI_ID_USER + 0x0B)
#define ID_MENU_FILE_NEW    (GUI_ID_USER +  1)
#define ID_MENU_FILE_OPEN   (GUI_ID_USER +  2)
#define ID_MENU_FILE_CLOSE  (GUI_ID_USER +  3)
#define ID_MENU_FILE_EXIT   (GUI_ID_USER +  4)
#define ID_MENU_FILE_RECENT (GUI_ID_USER +  5)
#define ID_MENU_RECENT_0    (GUI_ID_USER +  6)
#define ID_MENU_RECENT_1    (GUI_ID_USER +  7)
#define ID_MENU_RECENT_2    (GUI_ID_USER +  8)
#define ID_MENU_RECENT_3    (GUI_ID_USER +  9)
#define ID_MENU_EDIT_UNDO   (GUI_ID_USER + 10)
#define ID_MENU_EDIT_REDO   (GUI_ID_USER + 11)
#define ID_MENU_EDIT_COPY   (GUI_ID_USER + 12)
#define ID_MENU_EDIT_PASTE  (GUI_ID_USER + 13)
#define ID_MENU_EDIT_DELETE (GUI_ID_USER + 14)
#define ID_MENU_HELP_ABOUT  (GUI_ID_USER + 15)


#define DATE_DIS (WM_USER+1)
// USER START (Optionally insert additional defines)
// USER END
//extern GUI_CONST_STORAGE GUI_BITMAP bmlogo;
//extern GUI_CONST_STORAGE GUI_BITMAP bmQQ2;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
/*********************************************************************
*
*       _AddMenuItem
*/
static void _AddMenuItem(MENU_Handle hMenu, MENU_Handle hSubmenu, const char* pText, U16 Id, U16 Flags) {
	MENU_ITEM_DATA Item;

	Item.pText = pText;
	Item.hSubmenu = hSubmenu;
	Item.Flags = Flags;
	Item.Id = Id;
	MENU_AddItem(hMenu, &Item);
}
/*********************************************************************
*
*       _cbDialog
*/

extern CALENDAR_DATE Date;
extern int Hour;
extern int Min;
extern int Sec;

WM_HWIN WIN_Header;
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
//  WM_HWIN hWin;
//  MENU_Handle hMenu;
//  MENU_Handle hMenuFile;
//  MENU_Handle hMenuEdit;
//  MENU_Handle hMenuHelp;
//  MENU_Handle hMenuRecent;
  char p[12];
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
/*	  hWin = pMsg->hWin;
	 hMenu = MENU_CreateEx(10, 10, 40, 60, hWin, WM_CF_SHOW, MENU_CF_VERTICAL, 0);

	  // Create sub menus
	  //
	 hMenuFile = MENU_CreateEx(30, 0, 40, 100, hMenu, 0, MENU_CF_VERTICAL, 0);
	  hMenuEdit = MENU_CreateEx(30, 0, 0, 0, hMenu, 0, MENU_CF_VERTICAL, 0);
	  hMenuHelp = MENU_CreateEx(30, 0,0, 0, hMenu, 0, MENU_CF_VERTICAL, 0);
	  hMenuRecent = MENU_CreateEx(70, 0, 40, 80, hMenu, 0, MENU_CF_VERTICAL, 0);
	  // Add menu items to main menu
	  //
	  _AddMenuItem(hMenu, hMenuFile, "File", 0, 0);
	  _AddMenuItem(hMenu, hMenuEdit, "Edit", 0, 0);
	  _AddMenuItem(hMenu, hMenuHelp, "Help", 0, 0);
	  //
	  // Add menu items to menu 'Recent'
	  //
	  _AddMenuItem(hMenuRecent, 0, "File 1", ID_MENU_RECENT_0, 0);
	  _AddMenuItem(hMenuRecent, 0, "File 2", ID_MENU_RECENT_1, 0);
	  _AddMenuItem(hMenuRecent, 0, "File 3", ID_MENU_RECENT_2, 0);
	  _AddMenuItem(hMenuRecent, 0, "File 4", ID_MENU_RECENT_3, 0);
	  //
	  // Add menu items to menu 'File'
	  //
	  _AddMenuItem(hMenuFile, 0, "New", ID_MENU_FILE_NEW, 0);
	  _AddMenuItem(hMenuFile, 0, "Open", ID_MENU_FILE_OPEN, 0);
	  _AddMenuItem(hMenuFile, 0, "Close", ID_MENU_FILE_CLOSE, MENU_IF_DISABLED);
	  _AddMenuItem(hMenuFile, 0, 0, 0, MENU_IF_SEPARATOR);
	  _AddMenuItem(hMenuFile, hMenuRecent, "Files...", ID_MENU_FILE_RECENT, 0);
	  _AddMenuItem(hMenuFile, 0, 0, 0, MENU_IF_SEPARATOR);
	  _AddMenuItem(hMenuFile, 0, "Exit", ID_MENU_FILE_EXIT, 0);
	  //
	  // Add menu items to menu 'Edit'
	  //
	  _AddMenuItem(hMenuEdit, 0, "Undo", ID_MENU_EDIT_UNDO, 0);
	  _AddMenuItem(hMenuEdit, 0, "Redo", ID_MENU_EDIT_REDO, 0);
	  _AddMenuItem(hMenuEdit, 0, 0, 0, MENU_IF_SEPARATOR);
	  _AddMenuItem(hMenuEdit, 0, "Copy", ID_MENU_EDIT_COPY, 0);
	  _AddMenuItem(hMenuEdit, 0, "Paste", ID_MENU_EDIT_PASTE, 0);
	  _AddMenuItem(hMenuEdit, 0, "Delete", ID_MENU_EDIT_DELETE, 0);
	  //
	  // Add menu items to menu 'Help'
	  //
	  _AddMenuItem(hMenuHelp, 0, "About", ID_MENU_HELP_ABOUT, 0);
	  //*/


	
	  break;
  case WM_CREATE:
	  WM_CreateTimer(pMsg->hWin, 0, 10, 0);
	  break;
  case DATE_DIS:
	  WM_InvalidateWindow(pMsg->hWin);
	  break;
  case WM_TIMER:
	  if (Sec++ > 59)
	  {
		  Min++;
		  Sec = 0;
	  }
	  if (Min == 60)
	  {
		  Hour++;
		  Min = 0;
	  }
	  if (Hour == 24)
	  {
		  Hour = 0;
		  Date.Day++;
	  }
	  WM_RestartTimer(pMsg->Data.v, 1000);
	  WM_SendMessageNoPara(WIN_Header, DATE_DIS);
	  break;
  case WM_PAINT:
	  
//  GUI_DrawGradientH(0, 0, 1023, 79, 0x0080ff80, GUI_LIGHTBLUE);

	  GUI_DrawGradientV(0, 0, 800, 25, 0xFFCCCC, GUI_LIGHTBLUE);
//	  GUI_DrawGradientV(0, 26, 800, 50, GUI_BLUE, 0xFFCCCC);
	  GUI_DrawGradientV(0, 26, 800, 50, 0xFF7070, 0x00FF2020);
//	  if (Sec%10>5)
//	  GUI_DrawBitmap(&bmlogo, 10, 8);
//	  else
		  GUI_DrawBitmap(&bmQQlogo, 10, 2);

	  GUI_SetColor(GUI_BLACK);
	  GUI_SetFont(&GUI_Font20B_ASCII);
	  GUI_SetTextMode(GUI_TM_TRANS);
	  sprintf(p,"%d-%2d-%2d",Date.Year,Date.Month,Date.Day);
	  GUI_DispStringAt(p,700,6);
	  sprintf(p, "%4d:%2d:%2d", Hour,Min,Sec);
	  GUI_DispStringAt(p,700, 25);


	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MENU_0: // Notifications sent by 'Menu'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/



WM_HWIN CreateHeaderWindow(void);
WM_HWIN CreateHeaderWindow(void) {
  WM_HWIN hWin;

  hWin = WM_CreateWindow(0, 0, 800, 50, WM_CF_SHOW, _cbDialog, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

#define START 1
WM_HWIN CreateWinMain(void);
void MainTask(void) {
	int i, j;
		GUI_RECT Rect = { 304, 360, 496, 390 };
	WM_SetCreateFlags(WM_CF_MEMDEV);
	GUI_Init();
	Date.Year = 2017;
	Date.Month = 7;
	Date.Day = 7;
	Hour = 20;
	Min = 24;
	Sec = 35;

	BUTTON_SetDefaultSkin(BUTTON_SKIN_FLEX);
	HEADER_SetDefaultSkin(HEADER_SKIN_FLEX);
	SCROLLBAR_SetDefaultSkin(SCROLLBAR_SKIN_FLEX);
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
	SPINBOX_SetDefaultSkin(SPINBOX_SKIN_FLEX);
	FRAMEWIN_SetDefaultSkin(FRAMEWIN_SKIN_FLEX);
	SLIDER_SetDefaultSkin(SLIDER_SKIN_FLEX);
	DROPDOWN_SetDefaultSkin(DROPDOWN_SKIN_FLEX);
#if START

			GUI_DrawBitmap(&bmgitlogo, 290, 10);
			GUI_SetFont(&GUI_Font24B_ASCII);
			GUI_DispStringHCenterAt("Build software better, together.", 400, 310);
	for (i = 0; i < 3; i++)
	{
		for (j = 0; j < 65; j++)
		{

			GUI_SetColor(GUI_BLACK);
			GUI_FillRect(305,360,495,390);
			GUI_SetColor(GUI_WHITE);
			GUI_DrawRoundedFrame(300,355,500,395,10,2);
			GUI_SetClipRect(&Rect);
			GUI_DrawBitmap(&bmbar, 250 + j * 4, 360);
			GUI_SetClipRect(NULL);
			GUI_Delay(20);
		}
	}
#endif
	GUI_EnableAlpha(1);
//	CreateWin1();
	CreateWinMain();
	WIN_Header = CreateHeaderWindow();
	while (1) {
		GUI_Exec();

	}
}
/*************************** End of file ****************************/
