#ifndef _MYGUI_H
#define _MYGUI_H

extern GUI_CONST_STORAGE GUI_BITMAP bmQQ;

extern GUI_CONST_STORAGE GUI_BITMAP bmgit;

extern GUI_CONST_STORAGE GUI_BITMAP bmmail;

extern GUI_CONST_STORAGE GUI_BITMAP bmtarget;

extern GUI_CONST_STORAGE GUI_BITMAP bmwechat;

extern GUI_CONST_STORAGE GUI_BITMAP bmgame;

extern GUI_CONST_STORAGE GUI_BITMAP bmkeil;

extern GUI_CONST_STORAGE GUI_BITMAP bmapple;

extern GUI_CONST_STORAGE GUI_BITMAP bmQQlogo;







#endif

